name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: |
        mkdir build
        go test ./... -v -coverprofile build/coverage.txt -coverpkg=./...
        cat build/coverage.txt | grep -v '.pb.go' > build/coverage.out
        go tool cover -func build/coverage.out

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: build artifacts
        path: build 
   
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.txt

  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.31.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        run: |
          golangci-lint run
