name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: |
        go test ./... -v -coverprofile profile.cov -coverpkg=./...
        go tool cover -func profile.cov
      
    - name: Send coverage to coveralls
      uses: shogo82148/actions-goveralls@v1
      with: 
        path-to-profile: profile.cov
        parallel: true
        
    - name: Send coverage to CodeClimate    
      uses: paambaati/codeclimate-action@v2.7.4
      env: 
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with: 
        coverageLocations: profile.cov:gocov
  
  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.31.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        run: |
          golangci-lint run
